name: executorch-builder

on: [push]

jobs:
  repo-download:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: check the files from checkout 
        run: |
          ls -la
 
      - name: installing micromamba
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml
          init-shell: bash

      - name: clone executorch viable/strict branch
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          depth: 1
          branch: 'viable/strict'
          owner: 'pytorch'
          repository: 'executorch'

      - name: access the repository
        run: |
          cd executorch
          echo "repo cloned successfully"
      
      - name: install executorch with CORTEX_M backend
        env:
          args: "-DEXECUTORCH_BUILD_COREML=OFF -DEXECUTORCH_BUILD_CORTEX_M=ON -DEXECUTORCH_BUILD_XNNPACK=OFF"
        run: | 
          cd executorch
          ./install_executorch.sh
          python -m pip wheel . --no-build-isolation -v --wheel-dir=dist

      - name: installing tools requried for the backend and the runtime 
        run: |
          cd executorch
          examples/arm/setup.sh --i-agree-to-the-contained-eula
      
      - name: building c++ runtime for cortex-m 
        run: |
          cd executorch
          source examples/arm/arm-scratch/setup_path.sh
          cmake -G Ninja -B cmake-out --preset arm-baremetal
          cd cmake-out
          ninja -j $(nproc)

      - name: checking the c++ runtime files #jsut for checkign remove later  
        run: |
          cd executorch 
          ls 
          cd cmake-out
          ls
