name: executorch-builder

on: [push]

jobs:
  repo-download:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: check the files from checkout 
        run: |
          ls -la
 
      - name: installing micromamba
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml
          init-shell: bash

      - name: clone executorch viable/strict branch
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          depth: 1
          branch: 'viable/strict'
          owner: 'pytorch'
          repository: 'executorch'

      - name: access the repository
        run: |
          echo "cloned repo"
          cd executorch
          ls -la
          import numpy 
